name: arrow
homepage: "https://github.com/kirklink/arrow"
description: 'Dart api server.'
version: 0.1.0-nullsafety.0
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  http: ^0.13.1
  uri: ^1.0.0
  uuid: ^3.0.4
  path: ^1.8.0
  recase: ^4.0.0-nullsafety.0
  pointycastle: ^3.0.1
  rsa_pkcs: ^2.0.0
  logging: ^1.0.1

