name: arrow
author: "Kirk Linkletter <kirklinkletter@gmail.com>"
homepage: "https://github.com/kirklink/arrow"
description: 'Dart api server.'
version: 0.0.10
environment:
  sdk: '>=2.1.0 <3.0.0'
dependencies:
  http: '^0.12.0+4'
  uri: '^0.11.3+1'
  uuid: '^2.0.4'
  path: '^1.6.4'
  recase: '^3.0.0'
dev_dependencies:
  build_runner: any
