name: arrow
author: "Kirk Linkletter <kirklinkletter@gmail.com>"
homepage: "https://github.com/kirklink/arrow"
description: 'Dart api server.'
version: 0.0.7
environment:
  sdk: '>=2.1.0 <3.0.0'
dependencies:
  http: '^0.12.0+2'
  uri: '^0.11.3'
  uuid: '^2.0.1'
  path: '^1.6.2'
  recase: '^2.0.1'
  bottom_line: '^0.0.3'
dev_dependencies:
  build_runner: any
