name: arrow
description: 'Arrow prototype'
version: 0.0.1
environment:
  sdk: ^2.1.0
dependencies:
  uri: ^0.11.3
  uuid: ^2.0.1
  path: ^1.6.2
  recase: 2.0.0+1
  bottom_line:
    path: ../bottom_line
dev_dependencies:
  build_runner:
